CREATE TABLE IF NOT EXISTS sys_detection_standards (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  standard_code VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL,
  display_name VARCHAR(128) DEFAULT '',
  display_name_en VARCHAR(128) DEFAULT '',
  display_name_ja VARCHAR(128) DEFAULT '',
  project_id BIGINT UNSIGNED NULL,
  project_code VARCHAR(64) DEFAULT '',
  mode VARCHAR(64) DEFAULT '',
  version INT NOT NULL DEFAULT 1,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  remark VARCHAR(255) DEFAULT '',
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY uk_detection_standards_code (standard_code),
  INDEX idx_detection_standards_project_id (project_id),
  INDEX idx_detection_standards_project_code (project_code),
  INDEX idx_detection_standards_mode (mode),
  INDEX idx_detection_standards_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_detection_standard_items (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  standard_id BIGINT UNSIGNED NOT NULL,
  var_id BIGINT NOT NULL,
  var_name VARCHAR(128) NOT NULL,
  display_name VARCHAR(128) DEFAULT '',
  display_name_en VARCHAR(128) DEFAULT '',
  display_name_ja VARCHAR(128) DEFAULT '',
  check_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  store_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  required BOOLEAN NOT NULL DEFAULT FALSE,
  limit_ll DOUBLE NULL,
  limit_l DOUBLE NULL,
  limit_h DOUBLE NULL,
  limit_hh DOUBLE NULL,
  unit VARCHAR(32) DEFAULT '',
  decimal_places INT NOT NULL DEFAULT 2,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  INDEX idx_standard_items_standard_id (standard_id),
  INDEX idx_standard_items_var_id (var_id),
  INDEX idx_standard_items_check_enabled (check_enabled),
  INDEX idx_standard_items_store_enabled (store_enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS detection_run_standard_items (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  test_no VARCHAR(128) DEFAULT '',
  standard_id BIGINT UNSIGNED NOT NULL,
  standard_item_id BIGINT UNSIGNED NOT NULL,
  var_id BIGINT NOT NULL,
  var_name VARCHAR(128) NOT NULL,
  display_name VARCHAR(128) DEFAULT '',
  display_name_en VARCHAR(128) DEFAULT '',
  display_name_ja VARCHAR(128) DEFAULT '',
  check_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  store_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  required BOOLEAN NOT NULL DEFAULT FALSE,
  limit_ll DOUBLE NULL,
  limit_l DOUBLE NULL,
  limit_h DOUBLE NULL,
  limit_hh DOUBLE NULL,
  unit VARCHAR(32) DEFAULT '',
  decimal_places INT NOT NULL DEFAULT 2,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NULL,
  INDEX idx_run_standard_items_task_id (task_id),
  INDEX idx_run_standard_items_test_no (test_no),
  INDEX idx_run_standard_items_standard_id (standard_id),
  INDEX idx_run_standard_items_standard_item_id (standard_item_id),
  INDEX idx_run_standard_items_var_id (var_id),
  INDEX idx_run_standard_items_check_enabled (check_enabled),
  INDEX idx_run_standard_items_store_enabled (store_enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE sys_detection_tasks
  ADD COLUMN standard_id BIGINT UNSIGNED NULL AFTER status,
  ADD COLUMN standard_code VARCHAR(64) DEFAULT '' AFTER standard_id,
  ADD COLUMN standard_version INT NOT NULL DEFAULT 0 AFTER standard_code,
  ADD INDEX idx_detection_standard_id (standard_id);
