CREATE DATABASE IF NOT EXISTS spindle_edge DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE spindle_edge;

CREATE TABLE IF NOT EXISTS sys_gateways (
  id INT PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  broker VARCHAR(255) NOT NULL,
  client_id VARCHAR(128) NOT NULL,
  username VARCHAR(128) DEFAULT '',
  password VARCHAR(255) DEFAULT '',
  topic VARCHAR(255) NOT NULL,
  qos TINYINT UNSIGNED NOT NULL DEFAULT 1,
  parser_type VARCHAR(64) DEFAULT 'kingiot_kio',
  kio_client_id VARCHAR(128) DEFAULT '',
  kio_writer VARCHAR(128) DEFAULT '',
  kio_write_username VARCHAR(128) DEFAULT '',
  kio_write_password VARCHAR(255) DEFAULT '',
  setdata_topic VARCHAR(255) DEFAULT '',
  write_result_topic VARCHAR(255) DEFAULT '',
  query_all_topic VARCHAR(255) DEFAULT '',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_projects (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  project_code VARCHAR(64) NOT NULL,
  site_no VARCHAR(64) DEFAULT '',
  edge_instance_id VARCHAR(128) DEFAULT '',
  name VARCHAR(128) NOT NULL,
  display_name VARCHAR(128) DEFAULT '',
  display_name_en VARCHAR(128) DEFAULT '',
  display_name_ja VARCHAR(128) DEFAULT '',
  model_name VARCHAR(128) DEFAULT '',
  image_ref VARCHAR(255) DEFAULT '',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  blocked BOOLEAN NOT NULL DEFAULT FALSE,
  placeholder BOOLEAN NOT NULL DEFAULT FALSE,
  current_task_id BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY uk_projects_code (project_code),
  INDEX idx_projects_site_no (site_no),
  INDEX idx_projects_edge_instance_id (edge_instance_id),
  INDEX idx_projects_enabled (enabled),
  INDEX idx_projects_blocked (blocked)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_project_members (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  member_role VARCHAR(32) DEFAULT 'member',
  notify_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY uk_project_member (project_id, user_id),
  INDEX idx_project_members_project_id (project_id),
  INDEX idx_project_members_user_id (user_id),
  INDEX idx_project_members_notify_enabled (notify_enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_station_view_templates (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  template_uid VARCHAR(128) NOT NULL,
  template_code VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL,
  display_name VARCHAR(128) DEFAULT '',
  display_name_en VARCHAR(128) DEFAULT '',
  display_name_ja VARCHAR(128) DEFAULT '',
  version INT NOT NULL DEFAULT 1,
  status VARCHAR(32) NOT NULL DEFAULT 'published',
  owner_scope VARCHAR(32) NOT NULL DEFAULT 'edge',
  layout_json TEXT NULL,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY uk_station_view_templates_uid (template_uid),
  UNIQUE KEY uk_station_view_templates_code (template_code),
  INDEX idx_station_view_templates_status (status),
  INDEX idx_station_view_templates_owner_scope (owner_scope)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_station_view_regions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  template_uid VARCHAR(128) NOT NULL,
  region_key VARCHAR(64) NOT NULL,
  region_type VARCHAR(64) NOT NULL,
  layout_json TEXT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY uk_station_view_region (template_uid, region_key),
  INDEX idx_station_view_regions_template_uid (template_uid),
  INDEX idx_station_view_regions_sort_order (sort_order),
  INDEX idx_station_view_regions_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_station_view_items (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  template_uid VARCHAR(128) NOT NULL,
  region_key VARCHAR(64) NOT NULL,
  item_uid VARCHAR(128) NOT NULL,
  item_type VARCHAR(64) NOT NULL,
  binding_type VARCHAR(64) NOT NULL,
  binding_key VARCHAR(128) DEFAULT '',
  binding_json TEXT NULL,
  display_json TEXT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  visible BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY uk_station_view_items_uid (item_uid),
  INDEX idx_station_view_items_template_uid (template_uid),
  INDEX idx_station_view_items_region_key (region_key),
  INDEX idx_station_view_items_binding_type (binding_type),
  INDEX idx_station_view_items_binding_key (binding_key),
  INDEX idx_station_view_items_sort_order (sort_order),
  INDEX idx_station_view_items_visible (visible)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_station_view_assignments (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  template_uid VARCHAR(128) NOT NULL,
  target_type VARCHAR(32) NOT NULL,
  target_key VARCHAR(128) NOT NULL,
  priority INT NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY uk_station_view_assignment (target_type, target_key),
  INDEX idx_station_view_assignments_template_uid (template_uid),
  INDEX idx_station_view_assignments_target_type (target_type),
  INDEX idx_station_view_assignments_target_key (target_key),
  INDEX idx_station_view_assignments_priority (priority),
  INDEX idx_station_view_assignments_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_tags (
  var_id BIGINT PRIMARY KEY,
  gateway_id INT NOT NULL,
  source_topic VARCHAR(255) DEFAULT '',
  source_path VARCHAR(512) NOT NULL,
  source_type VARCHAR(32) NOT NULL DEFAULT 'mqtt',
  raw_name VARCHAR(255) NOT NULL,
  project_id BIGINT UNSIGNED NULL,
  project_code VARCHAR(64) DEFAULT '',
  var_group VARCHAR(128) DEFAULT '',
  var_name VARCHAR(128) NOT NULL,
  display_name VARCHAR(128) DEFAULT '',
  display_name_en VARCHAR(128) DEFAULT '',
  display_name_ja VARCHAR(128) DEFAULT '',
  json_path VARCHAR(512) NOT NULL,
  data_type VARCHAR(32) NOT NULL,
  unit VARCHAR(32) DEFAULT '',
  decimal_places INT NOT NULL DEFAULT 2,
  scale_factor DOUBLE NOT NULL DEFAULT 1,
  offset_val DOUBLE NOT NULL DEFAULT 0,
  rw_mode VARCHAR(8) NOT NULL DEFAULT 'R',
  writable BOOLEAN NOT NULL DEFAULT FALSE,
  write_source_id INT NOT NULL DEFAULT 0,
  write_path VARCHAR(512) DEFAULT '',
  write_data_type VARCHAR(32) DEFAULT '',
  write_min DOUBLE NULL,
  write_max DOUBLE NULL,
  write_enum TEXT NULL,
  write_requires_audit BOOLEAN NOT NULL DEFAULT TRUE,
  suspicious_value DOUBLE NULL,
  debounce_threshold DOUBLE NULL,
  debounce_ms INT NOT NULL DEFAULT 0,
  deadband DOUBLE NOT NULL DEFAULT 0,
  default_alarm_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  default_limit_ll DOUBLE NULL,
  default_limit_l DOUBLE NULL,
  default_limit_h DOUBLE NULL,
  default_limit_hh DOUBLE NULL,
  default_limit_deadband DOUBLE NOT NULL DEFAULT 0,
  default_violation_hold_ms INT NOT NULL DEFAULT 0,
  default_recover_hold_ms INT NOT NULL DEFAULT 0,
  discovered BOOLEAN NOT NULL DEFAULT TRUE,
  placeholder BOOLEAN NOT NULL DEFAULT FALSE,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY uk_gateway_source (gateway_id, source_path),
  INDEX idx_sys_tags_gateway_id (gateway_id),
  INDEX idx_sys_tags_project_id (project_id),
  INDEX idx_sys_tags_enabled (enabled),
  INDEX idx_sys_tags_source_type (source_type),
  INDEX idx_sys_tags_writable (writable),
  INDEX idx_sys_tags_default_alarm_enabled (default_alarm_enabled),
  INDEX idx_sys_tags_project_code (project_code),
  INDEX idx_sys_tags_var_group (var_group),
  INDEX idx_sys_tags_var_name (var_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_storage_routes (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL,
  var_id BIGINT NOT NULL,
  route_code VARCHAR(128) NOT NULL,
  storage_target VARCHAR(32) NOT NULL DEFAULT 'wide_table',
  table_name VARCHAR(128) NOT NULL,
  column_name VARCHAR(64) NOT NULL,
  column_type VARCHAR(32) NOT NULL,
  form_field_key VARCHAR(128) DEFAULT '',
  query_alias VARCHAR(128) DEFAULT '',
  trigger_mode VARCHAR(32) NOT NULL DEFAULT 'on_cycle',
  cycle_ms INT NOT NULL DEFAULT 0,
  deadband DOUBLE NOT NULL DEFAULT 0,
  store_on_start BOOLEAN NOT NULL DEFAULT FALSE,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY uk_storage_route_var_code (var_id, route_code),
  INDEX idx_storage_routes_project_id (project_id),
  INDEX idx_storage_routes_var_id (var_id),
  INDEX idx_storage_routes_storage_target (storage_target),
  INDEX idx_storage_routes_table_name (table_name),
  INDEX idx_storage_routes_column_name (column_name),
  INDEX idx_storage_routes_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_task_rules (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL,
  rule_code VARCHAR(128) NOT NULL,
  name VARCHAR(128) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  trigger_var_id BIGINT NOT NULL,
  trigger_operator VARCHAR(16) NOT NULL,
  trigger_value VARCHAR(255) NOT NULL,
  trigger_edge VARCHAR(16) NOT NULL DEFAULT 'any',
  action_type VARCHAR(64) NOT NULL,
  action_payload TEXT NULL,
  priority INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY uk_task_rules_code (rule_code),
  INDEX idx_task_rules_project_id (project_id),
  INDEX idx_task_rules_enabled (enabled),
  INDEX idx_task_rules_trigger_var_id (trigger_var_id),
  INDEX idx_task_rules_priority (priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_task_flows (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL,
  flow_code VARCHAR(128) NOT NULL,
  name VARCHAR(128) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  trigger_type VARCHAR(32) NOT NULL,
  condition_script TEXT NULL,
  action_type VARCHAR(64) NOT NULL,
  action_script TEXT NULL,
  action_payload TEXT NULL,
  steps_json TEXT NULL,
    timeout_ms INT NOT NULL DEFAULT 3000,
    cooldown_ms INT NOT NULL DEFAULT 0,
    hold_ms INT NOT NULL DEFAULT 0,
    schedule_interval_ms INT NOT NULL DEFAULT 0,
    priority INT NOT NULL DEFAULT 0,
  remark VARCHAR(255) DEFAULT '',
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY uk_task_flows_code (flow_code),
  INDEX idx_task_flows_project_id (project_id),
  INDEX idx_task_flows_enabled (enabled),
  INDEX idx_task_flows_trigger_type (trigger_type),
  INDEX idx_task_flows_priority (priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_task_flow_vars (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  flow_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  var_id BIGINT NOT NULL,
  var_name VARCHAR(128) DEFAULT '',
  role VARCHAR(32) NOT NULL DEFAULT 'watch',
  created_at DATETIME(3) NULL,
  INDEX idx_task_flow_vars_flow_id (flow_id),
  INDEX idx_task_flow_vars_project_id (project_id),
  INDEX idx_task_flow_vars_var_id (var_id),
  INDEX idx_task_flow_vars_role (role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS task_flow_runs (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  flow_id BIGINT UNSIGNED NOT NULL,
  flow_code VARCHAR(128) DEFAULT '',
  project_id BIGINT UNSIGNED NOT NULL,
  trigger_type VARCHAR(32) DEFAULT '',
  trigger_var_id BIGINT DEFAULT 0,
  origin_flow_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  origin_run_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  depth INT NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL,
  started_at DATETIME(3) NULL,
  finished_at DATETIME(3) NULL,
  duration_ms BIGINT NOT NULL DEFAULT 0,
  input_snapshot TEXT NULL,
  result_json TEXT NULL,
  error_message VARCHAR(1024) DEFAULT '',
  script_logs TEXT NULL,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  INDEX idx_task_flow_runs_flow_id (flow_id),
  INDEX idx_task_flow_runs_flow_code (flow_code),
  INDEX idx_task_flow_runs_project_id (project_id),
  INDEX idx_task_flow_runs_trigger_type (trigger_type),
  INDEX idx_task_flow_runs_trigger_var_id (trigger_var_id),
  INDEX idx_task_flow_runs_origin_flow_id (origin_flow_id),
  INDEX idx_task_flow_runs_origin_run_id (origin_run_id),
  INDEX idx_task_flow_runs_status (status),
  INDEX idx_task_flow_runs_started_at (started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS task_flow_sql_logs (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  run_id BIGINT UNSIGNED NOT NULL,
  flow_id BIGINT UNSIGNED NOT NULL,
  sql_text TEXT NOT NULL,
  sql_args TEXT NULL,
  affected_rows BIGINT NOT NULL DEFAULT 0,
  duration_ms BIGINT NOT NULL DEFAULT 0,
  error_message VARCHAR(1024) DEFAULT '',
  created_at DATETIME(3) NULL,
  INDEX idx_task_flow_sql_logs_run_id (run_id),
  INDEX idx_task_flow_sql_logs_flow_id (flow_id),
  INDEX idx_task_flow_sql_logs_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_detection_standards (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  standard_code VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL,
  display_name VARCHAR(128) DEFAULT '',
  display_name_en VARCHAR(128) DEFAULT '',
  display_name_ja VARCHAR(128) DEFAULT '',
  project_id BIGINT UNSIGNED NULL,
  project_code VARCHAR(64) DEFAULT '',
  mode VARCHAR(64) DEFAULT '',
  report_template_id BIGINT UNSIGNED NULL,
  version INT NOT NULL DEFAULT 1,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  remark VARCHAR(255) DEFAULT '',
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY uk_detection_standards_code (standard_code),
  INDEX idx_detection_standards_project_id (project_id),
  INDEX idx_detection_standards_project_code (project_code),
  INDEX idx_detection_standards_mode (mode),
  INDEX idx_detection_standards_report_template_id (report_template_id),
  INDEX idx_detection_standards_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_report_templates (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  template_code VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL,
  display_name VARCHAR(128) DEFAULT '',
  file_ref VARCHAR(512) NOT NULL,
  file_kind VARCHAR(32) NOT NULL DEFAULT 'xlsx',
  version INT NOT NULL DEFAULT 1,
  params_schema_json TEXT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  remark VARCHAR(255) DEFAULT '',
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY uk_report_templates_code (template_code),
  INDEX idx_report_templates_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_detection_standard_favorites (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  standard_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY uk_standard_favorite_user_standard (user_id, standard_id),
  INDEX idx_standard_favorites_user_id (user_id),
  INDEX idx_standard_favorites_standard_id (standard_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_detection_standard_recents (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  standard_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  last_used_at DATETIME(3) NULL,
  use_count INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY uk_standard_recent_user_standard_project (user_id, standard_id, project_id),
  INDEX idx_standard_recents_user_id (user_id),
  INDEX idx_standard_recents_standard_id (standard_id),
  INDEX idx_standard_recents_project_id (project_id),
  INDEX idx_standard_recents_last_used_at (last_used_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_detection_standard_items (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  standard_id BIGINT UNSIGNED NOT NULL,
  var_id BIGINT NOT NULL,
  var_name VARCHAR(128) NOT NULL,
  display_name VARCHAR(128) DEFAULT '',
  display_name_en VARCHAR(128) DEFAULT '',
  display_name_ja VARCHAR(128) DEFAULT '',
  check_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  alarm_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  store_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  check_cycle_ms INT NOT NULL DEFAULT 0,
  check_on_start BOOLEAN NOT NULL DEFAULT TRUE,
  required BOOLEAN NOT NULL DEFAULT FALSE,
  check_method VARCHAR(32) NOT NULL DEFAULT 'numeric_range',
  target_value VARCHAR(255) DEFAULT '',
  limit_ll DOUBLE NULL,
  limit_l DOUBLE NULL,
  limit_h DOUBLE NULL,
  limit_hh DOUBLE NULL,
  limit_deadband DOUBLE NOT NULL DEFAULT 0,
  violation_hold_ms INT NOT NULL DEFAULT 0,
  recover_hold_ms INT NOT NULL DEFAULT 0,
  quality_policy VARCHAR(32) NOT NULL DEFAULT 'ignore_bad',
  unit VARCHAR(32) DEFAULT '',
  decimal_places INT NOT NULL DEFAULT 2,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  INDEX idx_standard_items_standard_id (standard_id),
  INDEX idx_standard_items_var_id (var_id),
  INDEX idx_standard_items_check_enabled (check_enabled),
  INDEX idx_standard_items_alarm_enabled (alarm_enabled),
  INDEX idx_standard_items_store_enabled (store_enabled),
  INDEX idx_standard_items_check_cycle_ms (check_cycle_ms),
  INDEX idx_standard_items_check_method (check_method)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_detection_tasks (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  test_no VARCHAR(128) NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  project_code VARCHAR(64) DEFAULT '',
  mode VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  standard_id BIGINT UNSIGNED NULL,
  standard_code VARCHAR(64) DEFAULT '',
  standard_version INT NOT NULL DEFAULT 0,
  started_at DATETIME(3) NULL,
  ended_at DATETIME(3) NULL,
  limit_check_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  end_policy VARCHAR(32) NOT NULL DEFAULT 'manual',
  duration_sec INT NOT NULL DEFAULT 0,
  qualified_hold_ms INT NOT NULL DEFAULT 0,
  expected_end_at DATETIME(3) NULL,
  pause_started_at DATETIME(3) NULL,
  paused_duration_ms BIGINT NOT NULL DEFAULT 0,
  end_type VARCHAR(32) DEFAULT '',
  stop_reason VARCHAR(255) DEFAULT '',
  operator_note VARCHAR(512) DEFAULT '',
  custom_config_json TEXT NULL,
  template_ref VARCHAR(128) DEFAULT '',
  report_template_id BIGINT UNSIGNED NULL,
  report_template_code VARCHAR(64) DEFAULT '',
  report_template_version INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY uk_detection_test_no (test_no),
  INDEX idx_detection_project_id (project_id),
  INDEX idx_detection_project_code (project_code),
  INDEX idx_detection_standard_id (standard_id),
  INDEX idx_detection_report_template_id (report_template_id),
  INDEX idx_detection_status (status),
  INDEX idx_detection_end_policy (end_policy)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS detection_run_notes (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  note_type VARCHAR(32) NOT NULL DEFAULT 'memo',
  content TEXT NOT NULL,
  actor_type VARCHAR(32) DEFAULT '',
  actor_id VARCHAR(128) DEFAULT '',
  created_at DATETIME(3) NULL,
  INDEX idx_detection_run_notes_task_id (task_id),
  INDEX idx_detection_run_notes_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS detection_run_reports (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  template_id BIGINT UNSIGNED NULL,
  template_code VARCHAR(64) DEFAULT '',
  template_version INT NOT NULL DEFAULT 0,
  file_ref VARCHAR(512) NOT NULL,
  file_name VARCHAR(255) DEFAULT '',
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  generated_at DATETIME(3) NULL,
  error_message VARCHAR(512) DEFAULT '',
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  INDEX idx_detection_run_reports_task_id (task_id),
  INDEX idx_detection_run_reports_template_id (template_id),
  INDEX idx_detection_run_reports_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS detection_run_report_requests (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  test_no VARCHAR(128) DEFAULT '',
  project_id BIGINT UNSIGNED NOT NULL,
  project_code VARCHAR(64) DEFAULT '',
  template_id BIGINT UNSIGNED NULL,
  template_code VARCHAR(64) DEFAULT '',
  template_version INT NOT NULL DEFAULT 0,
  var_id BIGINT NOT NULL DEFAULT 0,
  var_name VARCHAR(128) NOT NULL,
  display_name VARCHAR(128) DEFAULT '',
  display_name_en VARCHAR(128) DEFAULT '',
  display_name_ja VARCHAR(128) DEFAULT '',
  report_name VARCHAR(128) DEFAULT '',
  variables_json TEXT NULL,
  params_json TEXT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  ext_1 VARCHAR(255) DEFAULT '',
  ext_2 VARCHAR(255) DEFAULT '',
  ext_3 VARCHAR(255) DEFAULT '',
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  INDEX idx_detection_run_report_requests_task_id (task_id),
  INDEX idx_detection_run_report_requests_project_id (project_id),
  INDEX idx_detection_run_report_requests_test_no (test_no),
  INDEX idx_detection_run_report_requests_template_id (template_id),
  INDEX idx_detection_run_report_requests_template_code (template_code),
  INDEX idx_detection_run_report_requests_var_id (var_id),
  INDEX idx_detection_run_report_requests_var_name (var_name),
  INDEX idx_detection_run_report_requests_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS detection_run_standard_items (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  test_no VARCHAR(128) DEFAULT '',
  standard_id BIGINT UNSIGNED NOT NULL,
  standard_item_id BIGINT UNSIGNED NOT NULL,
  var_id BIGINT NOT NULL,
  var_name VARCHAR(128) NOT NULL,
  display_name VARCHAR(128) DEFAULT '',
  display_name_en VARCHAR(128) DEFAULT '',
  display_name_ja VARCHAR(128) DEFAULT '',
  check_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  alarm_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  store_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  check_cycle_ms INT NOT NULL DEFAULT 0,
  check_on_start BOOLEAN NOT NULL DEFAULT TRUE,
  required BOOLEAN NOT NULL DEFAULT FALSE,
  check_method VARCHAR(32) NOT NULL DEFAULT 'numeric_range',
  target_value VARCHAR(255) DEFAULT '',
  limit_ll DOUBLE NULL,
  limit_l DOUBLE NULL,
  limit_h DOUBLE NULL,
  limit_hh DOUBLE NULL,
  limit_deadband DOUBLE NOT NULL DEFAULT 0,
  violation_hold_ms INT NOT NULL DEFAULT 0,
  recover_hold_ms INT NOT NULL DEFAULT 0,
  quality_policy VARCHAR(32) NOT NULL DEFAULT 'ignore_bad',
  variable_default_alarm_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  variable_default_limit_ll DOUBLE NULL,
  variable_default_limit_l DOUBLE NULL,
  variable_default_limit_h DOUBLE NULL,
  variable_default_limit_hh DOUBLE NULL,
  variable_default_limit_deadband DOUBLE NOT NULL DEFAULT 0,
  variable_default_violation_hold_ms INT NOT NULL DEFAULT 0,
  variable_default_recover_hold_ms INT NOT NULL DEFAULT 0,
  unit VARCHAR(32) DEFAULT '',
  decimal_places INT NOT NULL DEFAULT 2,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NULL,
  INDEX idx_run_standard_items_task_id (task_id),
  INDEX idx_run_standard_items_test_no (test_no),
  INDEX idx_run_standard_items_standard_id (standard_id),
  INDEX idx_run_standard_items_standard_item_id (standard_item_id),
  INDEX idx_run_standard_items_var_id (var_id),
  INDEX idx_run_standard_items_check_enabled (check_enabled),
  INDEX idx_run_standard_items_alarm_enabled (alarm_enabled),
  INDEX idx_run_standard_items_store_enabled (store_enabled),
  INDEX idx_run_standard_items_check_cycle_ms (check_cycle_ms),
  INDEX idx_run_standard_items_check_method (check_method)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS detection_run_storage_routes (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  test_no VARCHAR(128) DEFAULT '',
  project_id BIGINT UNSIGNED NOT NULL,
  var_id BIGINT NOT NULL,
  route_id BIGINT UNSIGNED NOT NULL,
  route_code VARCHAR(128) NOT NULL,
  storage_target VARCHAR(32) NOT NULL DEFAULT 'wide_table',
  table_name VARCHAR(128) NOT NULL,
  column_name VARCHAR(64) NOT NULL,
  column_type VARCHAR(32) NOT NULL,
  form_field_key VARCHAR(128) DEFAULT '',
  query_alias VARCHAR(128) DEFAULT '',
  trigger_mode VARCHAR(32) NOT NULL DEFAULT 'on_cycle',
  cycle_ms INT NOT NULL DEFAULT 0,
  deadband DOUBLE NOT NULL DEFAULT 0,
  store_on_start BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME(3) NULL,
  INDEX idx_run_storage_routes_task_id (task_id),
  INDEX idx_run_storage_routes_test_no (test_no),
  INDEX idx_run_storage_routes_project_id (project_id),
  INDEX idx_run_storage_routes_var_id (var_id),
  INDEX idx_run_storage_routes_route_id (route_id),
  INDEX idx_run_storage_routes_storage_target (storage_target),
  INDEX idx_run_storage_routes_table_name (table_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS detection_limit_alarms (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  scope VARCHAR(32) NOT NULL DEFAULT 'detection',
  task_id BIGINT UNSIGNED NOT NULL,
  test_no VARCHAR(128) DEFAULT '',
  project_id BIGINT UNSIGNED NOT NULL,
  project_code VARCHAR(64) DEFAULT '',
  standard_id BIGINT UNSIGNED NULL,
  standard_item_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  run_standard_item_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  var_id BIGINT NOT NULL,
  var_name VARCHAR(128) NOT NULL,
  display_name VARCHAR(128) DEFAULT '',
  display_name_en VARCHAR(128) DEFAULT '',
  display_name_ja VARCHAR(128) DEFAULT '',
  check_method VARCHAR(32) NOT NULL,
  alarm_type VARCHAR(32) NOT NULL,
  alarm_level VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  start_value DOUBLE NULL,
  peak_value DOUBLE NULL,
  recover_value DOUBLE NULL,
  limit_value DOUBLE NULL,
  limit_deadband DOUBLE NOT NULL DEFAULT 0,
  quality INT NOT NULL DEFAULT 1,
  first_seen_at DATETIME(3) NOT NULL,
  last_seen_at DATETIME(3) NOT NULL,
  recovered_at DATETIME(3) NULL,
  duration_ms BIGINT NOT NULL DEFAULT 0,
  message VARCHAR(512) DEFAULT '',
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  INDEX idx_limit_alarms_scope (scope),
  INDEX idx_limit_alarms_task_id (task_id),
  INDEX idx_limit_alarms_test_no (test_no),
  INDEX idx_limit_alarms_project_id (project_id),
  INDEX idx_limit_alarms_project_code (project_code),
  INDEX idx_limit_alarms_standard_id (standard_id),
  INDEX idx_limit_alarms_standard_item_id (standard_item_id),
  INDEX idx_limit_alarms_run_standard_item_id (run_standard_item_id),
  INDEX idx_limit_alarms_var_id (var_id),
  INDEX idx_limit_alarms_var_name (var_name),
  INDEX idx_limit_alarms_alarm_type (alarm_type),
  INDEX idx_limit_alarms_alarm_level (alarm_level),
  INDEX idx_limit_alarms_status (status),
  INDEX idx_limit_alarms_first_seen_at (first_seen_at),
  INDEX idx_limit_alarms_last_seen_at (last_seen_at),
  INDEX idx_limit_alarms_recovered_at (recovered_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS detection_run_events (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  test_no VARCHAR(128) DEFAULT '',
  project_id BIGINT UNSIGNED NOT NULL,
  project_code VARCHAR(64) DEFAULT '',
  event_type VARCHAR(64) NOT NULL,
  event_level VARCHAR(32) DEFAULT '',
  message VARCHAR(512) DEFAULT '',
  detail TEXT NULL,
  occurred_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NULL,
  INDEX idx_run_events_task_id (task_id),
  INDEX idx_run_events_test_no (test_no),
  INDEX idx_run_events_project_id (project_id),
  INDEX idx_run_events_project_code (project_code),
  INDEX idx_run_events_event_type (event_type),
  INDEX idx_run_events_event_level (event_level),
  INDEX idx_run_events_occurred_at (occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS detection_run_summaries (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL UNIQUE,
  test_no VARCHAR(128) DEFAULT '',
  project_id BIGINT UNSIGNED NOT NULL,
  project_code VARCHAR(64) DEFAULT '',
  result_status VARCHAR(32) NOT NULL,
  started_at DATETIME(3) NULL,
  ended_at DATETIME(3) NULL,
  duration_ms BIGINT NOT NULL DEFAULT 0,
  history_rows BIGINT NOT NULL DEFAULT 0,
  alarm_total BIGINT NOT NULL DEFAULT 0,
  alarm_active BIGINT NOT NULL DEFAULT 0,
  alarm_recovered BIGINT NOT NULL DEFAULT 0,
  alarm_above_h BIGINT NOT NULL DEFAULT 0,
  alarm_above_hh BIGINT NOT NULL DEFAULT 0,
  alarm_below_l BIGINT NOT NULL DEFAULT 0,
  alarm_below_ll BIGINT NOT NULL DEFAULT 0,
  first_alarm_at DATETIME(3) NULL,
  last_alarm_at DATETIME(3) NULL,
  last_refreshed_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  INDEX idx_run_summaries_test_no (test_no),
  INDEX idx_run_summaries_project_id (project_id),
  INDEX idx_run_summaries_project_code (project_code),
  INDEX idx_run_summaries_result_status (result_status),
  INDEX idx_run_summaries_last_refreshed_at (last_refreshed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS detection_run_features (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  test_no VARCHAR(128) DEFAULT '',
  project_id BIGINT UNSIGNED NOT NULL,
  project_code VARCHAR(64) DEFAULT '',
  var_id BIGINT NOT NULL,
  var_name VARCHAR(128) DEFAULT '',
  sample_count BIGINT NOT NULL DEFAULT 0,
  avg_value DOUBLE NULL,
  min_value DOUBLE NULL,
  max_value DOUBLE NULL,
  first_sample_time DATETIME(3) NULL,
  last_sample_time DATETIME(3) NULL,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY uk_detection_feature_task_var (task_id, var_id),
  INDEX idx_detection_features_project_id (project_id),
  INDEX idx_detection_features_var_id (var_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rt_history_data (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  gateway_id INT NOT NULL DEFAULT 0,
  topic VARCHAR(255) DEFAULT '',
  project_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  task_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  test_no VARCHAR(128) DEFAULT '',
  var_id BIGINT NOT NULL,
  var_name VARCHAR(128) NOT NULL,
  project_code VARCHAR(64) DEFAULT '',
  value DOUBLE NULL,
  str_value TEXT NULL,
  quality INT NOT NULL DEFAULT 1,
  source_time DATETIME(3) NOT NULL,
  created_at DATETIME(3) NULL,
  INDEX idx_history_source_time (source_time),
  INDEX idx_history_project_id (project_id),
  INDEX idx_history_task_id (task_id),
  INDEX idx_history_test_no (test_no),
  INDEX idx_history_var_id (var_id),
  INDEX idx_history_project_code (project_code),
  INDEX idx_history_gateway_id (gateway_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_users (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(32) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  permissions_version BIGINT NOT NULL DEFAULT 1,
  last_login_at DATETIME(3) NULL,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  INDEX idx_users_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_service_clients (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  client_id VARCHAR(128) NOT NULL UNIQUE,
  secret_hash VARCHAR(255) NOT NULL UNIQUE,
  scopes TEXT NOT NULL,
  allowed_cidrs TEXT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  expires_at DATETIME(3) NULL,
  last_used_at DATETIME(3) NULL,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  INDEX idx_service_clients_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_sso_tickets (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  ticket_hash VARCHAR(255) NOT NULL UNIQUE,
  user_id BIGINT UNSIGNED NOT NULL,
  role VARCHAR(32) NOT NULL,
  permissions_version BIGINT NOT NULL DEFAULT 1,
  edge_instance_id VARCHAR(128) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  used_at DATETIME(3) NULL,
  created_ip VARCHAR(64) DEFAULT '',
  created_at DATETIME(3) NULL,
  INDEX idx_sso_tickets_user_id (user_id),
  INDEX idx_sso_tickets_edge_instance_id (edge_instance_id),
  INDEX idx_sso_tickets_expires_at (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_audit_logs (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  actor_type VARCHAR(32) NOT NULL,
  actor_id VARCHAR(128) NOT NULL,
  action VARCHAR(128) NOT NULL,
  target_type VARCHAR(64) DEFAULT '',
  target_id VARCHAR(128) DEFAULT '',
  result VARCHAR(32) NOT NULL,
  detail JSON NULL,
  created_at DATETIME(3) NULL,
  INDEX idx_audit_actor_type (actor_type),
  INDEX idx_audit_actor_id (actor_id),
  INDEX idx_audit_action (action)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS edge_control_commands (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  command_id VARCHAR(128) NOT NULL,
  client_id VARCHAR(128) NOT NULL,
  operator_id VARCHAR(128) DEFAULT '',
  operator_name VARCHAR(128) DEFAULT '',
  operator_username VARCHAR(128) DEFAULT '',
  edge_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  action VARCHAR(128) NOT NULL,
  target_type VARCHAR(64) DEFAULT '',
  target_id VARCHAR(128) DEFAULT '',
  request_json JSON NULL,
  status VARCHAR(32) NOT NULL,
  result_json JSON NULL,
  error_code VARCHAR(128) DEFAULT '',
  error_message VARCHAR(512) DEFAULT '',
  received_at DATETIME(3) NOT NULL,
  completed_at DATETIME(3) NULL,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY uk_edge_control_command (client_id, command_id),
  INDEX idx_edge_control_client_id (client_id),
  INDEX idx_edge_control_operator_username (operator_username),
  INDEX idx_edge_control_edge_user_id (edge_user_id),
  INDEX idx_edge_control_action (action),
  INDEX idx_edge_control_status (status),
  INDEX idx_edge_control_received_at (received_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_notifications (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  event_uid VARCHAR(128) NOT NULL UNIQUE,
  type VARCHAR(64) NOT NULL,
  level VARCHAR(32) NOT NULL,
  target_type VARCHAR(32) NOT NULL,
  target_id VARCHAR(128) DEFAULT '',
  project_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  project_code VARCHAR(64) DEFAULT '',
  task_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  test_no VARCHAR(128) DEFAULT '',
  var_id BIGINT NOT NULL DEFAULT 0,
  var_name VARCHAR(128) DEFAULT '',
  display_name VARCHAR(128) DEFAULT '',
  message VARCHAR(512) DEFAULT '',
  payload JSON NULL,
  occurred_at DATETIME(3) NOT NULL,
  expires_at DATETIME(3) NULL,
  created_at DATETIME(3) NULL,
  INDEX idx_notifications_type (type),
  INDEX idx_notifications_level (level),
  INDEX idx_notifications_target_type (target_type),
  INDEX idx_notifications_target_id (target_id),
  INDEX idx_notifications_project_id (project_id),
  INDEX idx_notifications_project_code (project_code),
  INDEX idx_notifications_task_id (task_id),
  INDEX idx_notifications_test_no (test_no),
  INDEX idx_notifications_var_id (var_id),
  INDEX idx_notifications_var_name (var_name),
  INDEX idx_notifications_occurred_at (occurred_at),
  INDEX idx_notifications_expires_at (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_notification_recipients (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  notification_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  read_at DATETIME(3) NULL,
  created_at DATETIME(3) NULL,
  UNIQUE KEY uk_notification_recipient (notification_id, user_id),
  INDEX idx_notification_recipients_user_id (user_id),
  INDEX idx_notification_recipients_read_at (read_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO sys_gateways (id, name, broker, client_id, username, password, topic, qos, parser_type, kio_client_id, kio_writer, kio_write_username, kio_write_password, setdata_topic, write_result_topic, query_all_topic, enabled, created_at, updated_at)
VALUES (
  1,
  'default-kingiot-kio',
  'tcp://127.0.0.1:1883',
  'edge-local-kio',
  'Admin',
  'admin',
  'datachange_S_KIO_Project',
  2,
  'kingiot_kio',
  'S_KIO_Project',
  'edge-test',
  'sa',
  'C12E01F2A13FF5587E1E9E4AEDB8242D',
  'setdata_S_KIO_Project',
  'setdata_result_S_KIO_Project_edge-test',
  'Query_AllKIOTags_S_KIO_Project',
  TRUE,
  NOW(3),
  NOW(3)
)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  broker = VALUES(broker),
  client_id = VALUES(client_id),
  username = VALUES(username),
  password = VALUES(password),
  topic = VALUES(topic),
  qos = VALUES(qos),
  parser_type = VALUES(parser_type),
  kio_client_id = VALUES(kio_client_id),
  kio_writer = VALUES(kio_writer),
  kio_write_username = VALUES(kio_write_username),
  kio_write_password = VALUES(kio_write_password),
  setdata_topic = VALUES(setdata_topic),
  write_result_topic = VALUES(write_result_topic),
  query_all_topic = VALUES(query_all_topic),
  enabled = VALUES(enabled),
  updated_at = NOW(3);

INSERT INTO sys_projects (project_code, site_no, name, display_name, display_name_en, display_name_ja, model_name, enabled, blocked, placeholder, created_at, updated_at)
VALUES
  ('AC-01', 'PLC01', '1号精密空调', '1号精密空调', 'Precision AC 1', '精密空調1号機', '', TRUE, FALSE, TRUE, NOW(3), NOW(3)),
  ('AC-02', 'PLC02', '2号精密空调', '2号精密空调', 'Precision AC 2', '精密空調2号機', '', TRUE, FALSE, TRUE, NOW(3), NOW(3)),
  ('AC-03', 'PLC03', '3号精密空调', '3号精密空调', 'Precision AC 3', '精密空調3号機', '', TRUE, FALSE, TRUE, NOW(3), NOW(3)),
  ('AC-04', 'PLC04', '4号精密空调', '4号精密空调', 'Precision AC 4', '精密空調4号機', '', TRUE, FALSE, TRUE, NOW(3), NOW(3)),
  ('AC-05', 'PLC05', '5号精密空调', '5号精密空调', 'Precision AC 5', '精密空調5号機', '', TRUE, FALSE, TRUE, NOW(3), NOW(3)),
  ('AC-06', 'PLC06', '6号精密空调', '6号精密空调', 'Precision AC 6', '精密空調6号機', '', TRUE, FALSE, TRUE, NOW(3), NOW(3))
ON DUPLICATE KEY UPDATE
  site_no = VALUES(site_no),
  name = VALUES(name),
  display_name = VALUES(display_name),
  display_name_en = VALUES(display_name_en),
  display_name_ja = VALUES(display_name_ja),
  updated_at = NOW(3);

INSERT INTO sys_tags (var_id, gateway_id, source_topic, source_path, raw_name, project_id, project_code, var_group, var_name, display_name, json_path, data_type, unit, decimal_places, scale_factor, offset_val, discovered, enabled, created_at, updated_at)
SELECT 1001, 1, 'spindle/PLC01/data', 'supply_air.temp', 'temp', d.id, d.project_code, '吹出口参数', 'supply_air_temp', '送风温度', 'supply_air.temp', 'FLOAT', 'C', 2, 1, 0, TRUE, TRUE, NOW(3), NOW(3)
FROM sys_projects d WHERE d.project_code = 'AC-01'
ON DUPLICATE KEY UPDATE
  project_id = VALUES(project_id),
  project_code = VALUES(project_code),
  var_group = VALUES(var_group),
  var_name = VALUES(var_name),
  display_name = VALUES(display_name),
  json_path = VALUES(json_path),
  data_type = VALUES(data_type),
  unit = VALUES(unit),
  updated_at = NOW(3);

INSERT INTO sys_tags (var_id, gateway_id, source_topic, source_path, raw_name, project_id, project_code, var_group, var_name, display_name, json_path, data_type, unit, decimal_places, scale_factor, offset_val, discovered, enabled, created_at, updated_at)
SELECT 1002, 1, 'spindle/PLC01/data', 'supply_air.humidity', 'humidity', d.id, d.project_code, '吹出口参数', 'supply_air_humidity', '送风湿度', 'supply_air.humidity', 'FLOAT', '%RH', 2, 1, 0, TRUE, TRUE, NOW(3), NOW(3)
FROM sys_projects d WHERE d.project_code = 'AC-01'
ON DUPLICATE KEY UPDATE
  project_id = VALUES(project_id),
  project_code = VALUES(project_code),
  var_group = VALUES(var_group),
  var_name = VALUES(var_name),
  display_name = VALUES(display_name),
  json_path = VALUES(json_path),
  data_type = VALUES(data_type),
  unit = VALUES(unit),
  updated_at = NOW(3);

INSERT INTO sys_tags (var_id, gateway_id, source_topic, source_path, raw_name, project_id, project_code, var_group, var_name, display_name, json_path, data_type, unit, decimal_places, scale_factor, offset_val, discovered, enabled, created_at, updated_at)
SELECT 1003, 1, 'spindle/PLC01/data', 'status.running', 'running', d.id, d.project_code, '状态和结果参数', 'run_status', '运行状态', 'status.running', 'BOOL', '', 0, 1, 0, TRUE, TRUE, NOW(3), NOW(3)
FROM sys_projects d WHERE d.project_code = 'AC-01'
ON DUPLICATE KEY UPDATE
  project_id = VALUES(project_id),
  project_code = VALUES(project_code),
  var_group = VALUES(var_group),
  var_name = VALUES(var_name),
  display_name = VALUES(display_name),
  json_path = VALUES(json_path),
  data_type = VALUES(data_type),
  unit = VALUES(unit),
  updated_at = NOW(3);
